# # FROM node:latest
# FROM  nginx:latest
# # WORKDIR /app set the wrok dir
# # COPY .  .  copy all
# COPY index.html /usr/share/nginx/html/index.html
# # RUN npm install
# # RUN apt-get update
#
# # RUN apt-get install --no-install-recommends xdg-utils
#
# # RUN apt-get install -y --no-install-recommends links2
# # RUN xdg-open index.html
# EXPOSE 3000
# # port should be same in app too
# # CMD [ "node","index.js" ]
# Use a lightweight Python image
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the Python script into the container
COPY app.py .

# Set the default command to run the script
CMD ["python", "app.py"]
CMD ["sh", "-c", "python app.py && tail -f /dev/null"]
